version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - bear_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - bear_static:/data/static/
      - bear_media:/data/media/

  django:
    image: bear_django:4
    networks:
      - bear_network
    volumes:
      - bear_static:/home/self/staticfiles/
      - bear_media:/home/self/media/
    secrets:
      - DJANGO_SECRET_KEY

  mariadb:
    image: mariadb:10.5
    networks:
      - bear_network
    volumes:
      - bear_mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password


networks:
  bear_network:

volumes:
  bear_static:
  bear_media:
  bear_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true